# Form implementation generated from reading ui file 'choise_profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log_in_another_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.log_in_another_profile.setGeometry(QtCore.QRect(150, 450, 211, 41))
        self.log_in_another_profile.setObjectName("log_in_another_profile")
        self.create_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_profile.setGeometry(QtCore.QRect(150, 520, 211, 41))
        self.create_profile.setObjectName("create_profile")
        self.delete_all_profiles = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_all_profiles.setGeometry(QtCore.QRect(150, 380, 211, 41))
        self.delete_all_profiles.setObjectName("delete_all_profiles")
        self.choise_profile = QtWidgets.QLabel(parent=self.centralwidget)
        self.choise_profile.setGeometry(QtCore.QRect(150, 40, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.choise_profile.setFont(font)
        self.choise_profile.setObjectName("choise_profile")
        self.profile_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.profile_1.setGeometry(QtCore.QRect(150, 90, 81, 81))
        self.profile_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.profile_1.setObjectName("profile_1")
        self.profile_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.profile_2.setGeometry(QtCore.QRect(280, 90, 81, 81))
        self.profile_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.profile_2.setObjectName("profile_2")
        self.profile_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.profile_3.setGeometry(QtCore.QRect(280, 200, 81, 81))
        self.profile_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.profile_3.setObjectName("profile_3")
        self.profile_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.profile_4.setGeometry(QtCore.QRect(150, 200, 81, 81))
        self.profile_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.profile_4.setObjectName("profile_4")
        self.log_in_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.log_in_profile.setGeometry(QtCore.QRect(50, 310, 181, 41))
        self.log_in_profile.setObjectName("log_in_profile")
        self.delete_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_profile.setGeometry(QtCore.QRect(280, 310, 181, 41))
        self.delete_profile.setObjectName("delete_profile")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "choise_profile"))
        self.log_in_another_profile.setText(_translate("MainWindow", "Войти в другой профиль"))
        self.create_profile.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.delete_all_profiles.setText(_translate("MainWindow", "Удалить все профили"))
        self.choise_profile.setText(_translate("MainWindow", "Выберите профиль для входа"))
        self.profile_1.setText(_translate("MainWindow", "Профиль 1"))
        self.profile_2.setText(_translate("MainWindow", "Профиль 2"))
        self.profile_3.setText(_translate("MainWindow", "Профиль 4"))
        self.profile_4.setText(_translate("MainWindow", "Профиль 3"))
        self.log_in_profile.setText(_translate("MainWindow", "Перейти в выбранный профиль"))
        self.delete_profile.setText(_translate("MainWindow", "Удалить профиль"))
