# Form implementation generated from reading ui file 'editing_tasks_panel.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 775)
        font = QtGui.QFont()
        font.setKerning(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ToDoList = QtWidgets.QLabel(parent=self.centralwidget)
        self.ToDoList.setGeometry(QtCore.QRect(40, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ToDoList.setFont(font)
        self.ToDoList.setObjectName("ToDoList")
        self.today_date = QtWidgets.QLabel(parent=self.centralwidget)
        self.today_date.setGeometry(QtCore.QRect(300, 30, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.today_date.setFont(font)
        self.today_date.setObjectName("today_date")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 600, 271, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_task = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.add_task.setFont(font)
        self.add_task.setObjectName("add_task")
        self.verticalLayout.addWidget(self.add_task)
        self.save_task_change = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.save_task_change.setFont(font)
        self.save_task_change.setObjectName("save_task_change")
        self.verticalLayout.addWidget(self.save_task_change)
        self.back_to_group_tasks = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.back_to_group_tasks.setFont(font)
        self.back_to_group_tasks.setObjectName("back_to_group_tasks")
        self.verticalLayout.addWidget(self.back_to_group_tasks)
        self.back_to_main_panel = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.back_to_main_panel.setFont(font)
        self.back_to_main_panel.setObjectName("back_to_main_panel")
        self.verticalLayout.addWidget(self.back_to_main_panel)
        self.delete_task = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.delete_task.setFont(font)
        self.delete_task.setObjectName("delete_task")
        self.verticalLayout.addWidget(self.delete_task)
        self.text_of_task = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_of_task.setGeometry(QtCore.QRect(40, 390, 421, 191))
        self.text_of_task.setObjectName("text_of_task")
        self.deadline = QtWidgets.QLabel(parent=self.centralwidget)
        self.deadline.setGeometry(QtCore.QRect(40, 350, 111, 20))
        self.deadline.setMaximumSize(QtCore.QSize(180, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.deadline.setFont(font)
        self.deadline.setObjectName("deadline")
        self.deadline_of_task = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.deadline_of_task.setGeometry(QtCore.QRect(180, 350, 281, 31))
        self.deadline_of_task.setUndoRedoEnabled(True)
        self.deadline_of_task.setReadOnly(False)
        self.deadline_of_task.setObjectName("deadline_of_task")
        self.name_of_task = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.name_of_task.setGeometry(QtCore.QRect(40, 300, 421, 31))
        self.name_of_task.setObjectName("name_of_task")
        self.name_of_folder_with_task = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.name_of_folder_with_task.setGeometry(QtCore.QRect(40, 250, 421, 31))
        self.name_of_folder_with_task.setObjectName("name_of_folder_with_task")
        self.name_of_project = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.name_of_project.setGeometry(QtCore.QRect(40, 200, 421, 31))
        self.name_of_project.setObjectName("name_of_project")
        self.tag_of_task = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tag_of_task.setGeometry(QtCore.QRect(40, 110, 421, 31))
        self.tag_of_task.setObjectName("tag_of_task")
        self.name_profile = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_profile.setGeometry(QtCore.QRect(50, 70, 151, 16))
        self.name_profile.setObjectName("name_profile")
        self.tag_of_project = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tag_of_project.setGeometry(QtCore.QRect(40, 150, 421, 31))
        self.tag_of_project.setObjectName("tag_of_project")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do List editing task"))
        self.ToDoList.setText(_translate("MainWindow", "To Do List"))
        self.today_date.setText(_translate("MainWindow", "Дата ДД/ММММ/ГГГГ"))
        self.add_task.setText(_translate("MainWindow", "Добавить задание"))
        self.save_task_change.setText(_translate("MainWindow", "Сохранить изменения"))
        self.back_to_group_tasks.setText(_translate("MainWindow", "Вернуться к группам задач"))
        self.back_to_main_panel.setText(_translate("MainWindow", "Вернуться на главную панель"))
        self.delete_task.setText(_translate("MainWindow", "Удалить задачу"))
        self.text_of_task.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Содержимое задачи</p></body></html>"))
        self.deadline.setText(_translate("MainWindow", "Выполнить до: "))
        self.deadline_of_task.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Время, Дата ДД/ММММ/ГГГГ</p></body></html>"))
        self.name_of_task.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Название задачи</p></body></html>"))
        self.name_of_folder_with_task.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Название папки с задачей</p></body></html>"))
        self.name_of_project.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&quot;Название проекта&quot;</p></body></html>"))
        self.tag_of_task.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тэг задачи</p></body></html>"))
        self.name_profile.setText(_translate("MainWindow", "Имя профиля"))
        self.tag_of_project.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тэг проекта</p></body></html>"))
