# Form implementation generated from reading ui file 'main_panel.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 724)
        font = QtGui.QFont()
        font.setKerning(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ToDoList = QtWidgets.QLabel(parent=self.centralwidget)
        self.ToDoList.setGeometry(QtCore.QRect(40, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ToDoList.setFont(font)
        self.ToDoList.setObjectName("ToDoList")
        self.today_date = QtWidgets.QLabel(parent=self.centralwidget)
        self.today_date.setGeometry(QtCore.QRect(300, 30, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.today_date.setFont(font)
        self.today_date.setObjectName("today_date")
        self.tasks_main_panel = QtWidgets.QLabel(parent=self.centralwidget)
        self.tasks_main_panel.setGeometry(QtCore.QRect(40, 80, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tasks_main_panel.setFont(font)
        self.tasks_main_panel.setObjectName("tasks_main_panel")
        self.failed_task = QtWidgets.QPushButton(parent=self.centralwidget)
        self.failed_task.setGeometry(QtCore.QRect(40, 550, 419, 41))
        self.failed_task.setObjectName("failed_task")
        self.button_change_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_change_profile.setGeometry(QtCore.QRect(410, 630, 51, 51))
        self.button_change_profile.setMaximumSize(QtCore.QSize(51, 51))
        self.button_change_profile.setObjectName("button_change_profile")
        self.button_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_settings.setGeometry(QtCore.QRect(40, 630, 51, 51))
        self.button_settings.setMaximumSize(QtCore.QSize(51, 51))
        self.button_settings.setObjectName("button_settings")
        self.button_change_project = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_change_project.setGeometry(QtCore.QRect(160, 630, 51, 51))
        self.button_change_project.setMaximumSize(QtCore.QSize(51, 51))
        self.button_change_project.setObjectName("button_change_project")
        self.button_create_new_folder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_create_new_folder.setGeometry(QtCore.QRect(280, 630, 51, 51))
        self.button_create_new_folder.setMaximumSize(QtCore.QSize(51, 51))
        self.button_create_new_folder.setObjectName("button_create_new_folder")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 160, 441, 371))
        self.listWidget.setObjectName("listWidget")
        self.Title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(20, 110, 341, 31))
        self.Title.setObjectName("Title")
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(380, 110, 81, 31))
        self.searchButton.setObjectName("searchButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do List main panel"))
        self.ToDoList.setText(_translate("MainWindow", "To Do List"))
        self.today_date.setText(_translate("MainWindow", "Дата ДД/ММММ/ГГГГ"))
        self.tasks_main_panel.setText(_translate("MainWindow", "Задачи (Главная панель)"))
        self.failed_task.setText(_translate("MainWindow", "Статистика по выполненным задачам"))
        self.button_change_profile.setText(_translate("MainWindow", "Profile"))
        self.button_settings.setText(_translate("MainWindow", "Settings"))
        self.button_change_project.setText(_translate("MainWindow", "Projects"))
        self.button_create_new_folder.setText(_translate("MainWindow", "+"))
        self.searchButton.setText(_translate("MainWindow", "Искать"))
