# Form implementation generated from reading ui file 'main_panel.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(507, 724)
        font = QtGui.QFont()
        font.setKerning(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ToDoList = QtWidgets.QLabel(parent=self.centralwidget)
        self.ToDoList.setGeometry(QtCore.QRect(40, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ToDoList.setFont(font)
        self.ToDoList.setObjectName("ToDoList")
        self.today_date = QtWidgets.QLabel(parent=self.centralwidget)
        self.today_date.setGeometry(QtCore.QRect(300, 30, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.today_date.setFont(font)
        self.today_date.setObjectName("today_date")
        self.tasks_main_panel = QtWidgets.QLabel(parent=self.centralwidget)
        self.tasks_main_panel.setGeometry(QtCore.QRect(40, 210, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tasks_main_panel.setFont(font)
        self.tasks_main_panel.setObjectName("tasks_main_panel")
        self.task_n1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.task_n1.setGeometry(QtCore.QRect(40, 250, 419, 41))
        self.task_n1.setObjectName("task_n1")
        self.task_n3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.task_n3.setGeometry(QtCore.QRect(40, 370, 419, 41))
        self.task_n3.setObjectName("task_n3")
        self.task_n2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.task_n2.setGeometry(QtCore.QRect(40, 310, 419, 41))
        self.task_n2.setObjectName("task_n2")
        self.completed_task = QtWidgets.QPushButton(parent=self.centralwidget)
        self.completed_task.setGeometry(QtCore.QRect(40, 490, 419, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.completed_task.setFont(font)
        self.completed_task.setObjectName("completed_task")
        self.failed_task = QtWidgets.QPushButton(parent=self.centralwidget)
        self.failed_task.setGeometry(QtCore.QRect(40, 550, 419, 41))
        self.failed_task.setObjectName("failed_task")
        self.button_change_profile = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_change_profile.setGeometry(QtCore.QRect(410, 630, 51, 51))
        self.button_change_profile.setMaximumSize(QtCore.QSize(51, 51))
        self.button_change_profile.setObjectName("button_change_profile")
        self.button_settings = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_settings.setGeometry(QtCore.QRect(40, 630, 51, 51))
        self.button_settings.setMaximumSize(QtCore.QSize(51, 51))
        self.button_settings.setObjectName("button_settings")
        self.task_n3_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.task_n3_2.setGeometry(QtCore.QRect(40, 430, 419, 41))
        self.task_n3_2.setObjectName("task_n3_2")
        self.button_change_project = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_change_project.setGeometry(QtCore.QRect(160, 630, 51, 51))
        self.button_change_project.setMaximumSize(QtCore.QSize(51, 51))
        self.button_change_project.setObjectName("button_change_project")
        self.name_of_project = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.name_of_project.setGeometry(QtCore.QRect(40, 160, 421, 31))
        self.name_of_project.setObjectName("name_of_project")
        self.button_create_new_folder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_create_new_folder.setGeometry(QtCore.QRect(280, 630, 51, 51))
        self.button_create_new_folder.setMaximumSize(QtCore.QSize(51, 51))
        self.button_create_new_folder.setObjectName("button_create_new_folder")
        self.name_profile = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_profile.setGeometry(QtCore.QRect(40, 70, 151, 16))
        self.name_profile.setObjectName("name_profile")
        self.tag_of_project = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.tag_of_project.setGeometry(QtCore.QRect(40, 110, 421, 31))
        self.tag_of_project.setObjectName("tag_of_project")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do List main panel"))
        self.ToDoList.setText(_translate("MainWindow", "To Do List"))
        self.today_date.setText(_translate("MainWindow", "Дата ДД/ММММ/ГГГГ"))
        self.tasks_main_panel.setText(_translate("MainWindow", "Задачи (Главная панель)"))
        self.task_n1.setText(_translate("MainWindow", "Входящие (без категорий и дэдлайнов)"))
        self.task_n3.setText(_translate("MainWindow", "Ближайшие (выполнить в ближайшую неделю)"))
        self.task_n2.setText(_translate("MainWindow", "Сегодняшние (выполнить сегодня)"))
        self.completed_task.setText(_translate("MainWindow", "Раскрыть последнюю выполненную (любую) задачу"))
        self.failed_task.setText(_translate("MainWindow", "Раскрыть последнюю проваленную (любую) задачу"))
        self.button_change_profile.setText(_translate("MainWindow", "Profile"))
        self.button_settings.setText(_translate("MainWindow", "Settings"))
        self.task_n3_2.setText(_translate("MainWindow", "Пользовательские папки задач"))
        self.button_change_project.setText(_translate("MainWindow", "Projects"))
        self.name_of_project.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&quot;Название проекта&quot;</p></body></html>"))
        self.button_create_new_folder.setText(_translate("MainWindow", "+"))
        self.name_profile.setText(_translate("MainWindow", "Имя профиля"))
        self.tag_of_project.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Тэг проекта</p></body></html>"))
